---

  - name: Install ZSH & GIT
    package: 
      name: "{{ item }}"
      state: latest
    with_items:
    - git
    - zsh
    
  - name: Add standard user to sudo group.
    user:
      name: lucas
      state: present
      shell: /bin/zsh
      comment: "Standard user with sudo for lucas"
      groups: sudo
      append: yes

  - name: Clone oh-my-zsh repo
    git: 
      repo: https://github.com/robbyrussell/oh-my-zsh.git
      dest: /home/lucas/.oh-my-zsh
 
  - name: deploy .zshrc
    template:
      src: zshrc
      dest:  /home/lucas/.zshrc
      owner: lucas

  - name: Add ansible standard user to sudo group.
    user:
      name: ansible
      state: present
      comment: "User for ansible automation"
      groups: sudo
      append: yes

  - name: Add standard user ssh keys.
    authorized_key:
      user: lucas
      key: "{{ item }}"
    with_items:
      - https://github.com/lucasmaurice.keys

  - name: Add ansible standard user ssh keys.
    authorized_key:
      user: ansible
      key: "{{ item }}"
    with_items:
      - https://github.com/lucasmaurice.keys

  - name: Allow privilege escalation without password.
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo ALL\='
      line: '%sudo ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
