---
ansible_host: 192.168.1.221
nodejs_install_npm_user: "root"
MOTD_PRIVATE_INTERFACE: eth0

temp_sql_user: api
temp_sql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61323533326638653531663562633265373830643432663238623763333738323730616438633230
          6334633236633466333663633135303364373735333331370a626564363131343539333531353433
          61353338386339653365616431616639616534366233383865323862613536326139313031343164
          6564323631343830300a366638353933306663306564313962303365663236346433326433646430
          33336162663032343630643631353265636461643834323433343937333635386335

nodejs_applications:
- name: domoserv
  repo: https://github.com/lucasmaurice/domotic_server.git
  index_file: bin/www
  env:
  - name: APP_PORT
    value: 8080
  - name: MYSQL_HOST
    value: localhost
  - name: MYSQL_USERNAME
    value: "{{temp_sql_user}}"
  - name: MYSQL_PASSWORD
    value: "{{temp_sql_password}}"

# Databases.
mysql_databases:
- name: home
  collation: utf8_general_ci
  encoding: utf8

# Users.
mysql_users:
- name: "{{temp_sql_user}}"
  host: 127.0.0.1
  password: "{{temp_sql_password}}"
  priv: '*.*:ALL'

mysql_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63616238663466623132663734303565376430326630353532346632343132656239386232386662
          3334613334336661636437653637346630346264343832350a356465376332336333353833313333
          66323538313866663035653536316235373166643461336132326363346637356666303662346430
          3661373863313536620a373035663831663365323736376430356636326334646632353965373664
          31393339363330303765613431353435393436663336346234633439363533316265
mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63616238663466623132663734303565376430326630353532346632343132656239386232386662
          3334613334336661636437653637346630346264343832350a356465376332336333353833313333
          66323538313866663035653536316235373166643461336132326363346637356666303662346430
          3661373863313536620a373035663831663365323736376430356636326334646632353965373664
          31393339363330303765613431353435393436663336346234633439363533316265
